# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  name: Default

steps:

- script: |
    rvm use 2.4.0
    gem install bundler
    bundle install 
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
